name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install lcov
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          mkdir -p test-results
          forge test -vvv > test-results/test-output.txt
        id: test

      - name: Generate coverage report
        run: |
          forge coverage --report lcov --ir-minimum > coverage.txt
          genhtml lcov.info -o coverage-report
          echo "COVERAGE=$(grep -oP 'TOTAL.*?(\d+\.\d+)%' coverage-report/index.html | grep -oP '\d+\.\d+')" >> $GITHUB_ENV

      - name: Extract coverage table
        run: |
          awk '/┌/{flag=1} flag; /└/{flag=0}' coverage.txt > coverage-table.txt

      - name: Insert coverage table into README
        run: |
          awk '/<!-- COVERAGE-TABLE-START -->/{print; system("cat coverage-table.txt"); skip=1} /<!-- COVERAGE-TABLE-END -->/{skip=0} !skip' README.md > README.new.md
          mv README.new.md README.md

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: error

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report
          if-no-files-found: error

      - name: Commit coverage table to README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update coverage table in README"
          file_pattern: README.md
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
